In [2]:
import numpy as np

def input_matrix(name):
    rows = int(input(f"Enter number of rows for {name}: "))
    cols = int(input(f"Enter number of columns for {name}: "))
    
    print(f"Enter elements row by row for {name}:")
    elements = []
    for i in range(rows):
        row = list(map(float, input(f"Row {i+1}: ").split()))
        elements.append(row)
    
    return np.array(elements)

def matrix_multiplication(A, B):
    if A.shape[1] != B.shape[0]:
        raise ValueError("Matrix multiplication not possible: Columns of A must equal rows of B")
    return np.dot(A, B)

A = input_matrix("Matrix A")
B = input_matrix("Matrix B")
try:
    result = matrix_multiplication(A, B)
    print("\nMatrix A:\n", A)
    print("\nMatrix B:\n", B)
    print("\nResult of A x B:\n", result)
except ValueError as e:
    print("\nError:", e)


Enter number of rows for Matrix A:  2
Enter number of columns for Matrix A:  2


Enter elements row by row for Matrix A:


Row 1:  2 7
Row 2:  3 5
Enter number of rows for Matrix B:  2
Enter number of columns for Matrix B:  2


Enter elements row by row for Matrix B:


Row 1:  9 4
Row 2:  4 7



Matrix A:
 [[2. 7.]
 [3. 5.]]

Matrix B:
 [[9. 4.]
 [4. 7.]]

Result of A x B:
 [[46. 57.]
 [47. 47.]]


In [3]:
import pandas as pd
data = pd.Series([50, 20, 30, 80, 100])
print("Original Data:\n", data)

# Min-Max Scaling
min_max_scaled = (data - data.min()) / (data.max() - data.min())
print("\nMin-Max Scaled Data:\n", min_max_scaled)

# Standardization (Z-score)
standardized = (data - data.mean()) / data.std()
print("\nStandardized Data:\n", standardized)


Original Data:
 0     50
1     20
2     30
3     80
4    100
dtype: int64

Min-Max Scaled Data:
 0    0.375
1    0.000
2    0.125
3    0.750
4    1.000
dtype: float64

Standardized Data:
 0   -0.178489
1   -1.070935
2   -0.773453
3    0.713957
4    1.308921
dtype: float64
